"""作品に親の作品を持たせる

Revision ID: 7a0189375695
Revises: c5c27ccd1e65
Create Date: 2026-09-30 00:45:24.265168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a0189375695'
down_revision: Union[str, Sequence[str], None] = 'c5c27ccd1e65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_story_id', sa.Integer(), nullable=True, comment='親の作品。章・外伝は親の作品の子にする'))
        batch_op.create_foreign_key('fk_story_parent_story_id_story', 'story', ['parent_story_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_constraint('fk_story_parent_story_id_story', type_='foreignkey')
        batch_op.drop_column('parent_story_id')

    # ### end Alembic commands ###
