"""claude を叩く入口の待ち行列 ai_task と ルーチンの生存確認 ai_worker を足す

Revision ID: 70f7710679d8
Revises: 68d73c9feb64
Create Date: 2026-09-30 17:31:53.086321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70f7710679d8'
down_revision: Union[str, Sequence[str], None] = '68d73c9feb64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_worker',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session', sa.String(), nullable=True, comment='ルーチンのセッション(分からなければ空)'),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=False),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entrance', sa.String(), nullable=False, comment='呼ぶ入口(`gui/api/interface.py` の id。例: episode.generate_episode.GenerateEpisode)'),
    sa.Column('args', sa.JSON(), nullable=False, comment='入口に渡す引数(JSON)'),
    sa.Column('status', sa.String(), nullable=False, comment='queued / running / done / failed'),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False, comment='拾った回数。ルーチンが途中で止まって拾い直すたびに増え、上限を超えたら failed にする'),
    sa.Column('result', sa.JSON(none_as_null=True), nullable=True, comment='入口の結果(JSON)'),
    sa.Column('error', sa.String(), nullable=True, comment='落ちた理由'),
    sa.Column('worker_id', sa.Integer(), nullable=True, comment='拾ったルーチン'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('fired_at', sa.DateTime(), nullable=True, comment='この行のためにルーチンを起こした時刻(起こしていなければ空)'),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['ai_worker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_task_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_task_status'))

    op.drop_table('ai_task')
    op.drop_table('ai_worker')
    # ### end Alembic commands ###
