"""話の要約から文体の覚え書きを外す

Revision ID: c5c27ccd1e65
Revises: d8f359a0f934
Create Date: 2026-09-29 21:55:18.035172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5c27ccd1e65'
down_revision: Union[str, Sequence[str], None] = 'd8f359a0f934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode_summary', schema=None) as batch_op:
        batch_op.drop_column('style')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('style', sa.VARCHAR(), nullable=False, server_default='', comment='文体の覚え書き'))

    # ### end Alembic commands ###
