"""画面からの AI の待ち行列 ai_task を消す

画面の AI のボタン(AI で作成・本文まで書く・推敲など)を外したので、その呼び出しを積んでいた待ち行列も要らなくなった。
AI は Claude のセッションが自分で回す。推敲の生成関数も無くしたので、`episode_character.mentioned` の注記から推敲を外す。

Revision ID: 491ed94816d6
Revises: e7f2aa3d09df
Create Date: 2026-10-02 15:51:37.636638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '491ed94816d6'
down_revision: Union[str, Sequence[str], None] = 'e7f2aa3d09df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_task_status'), table_name='ai_task')
    op.drop_table('ai_task')
    op.alter_column('episode_character', 'mentioned',
               existing_type=sa.BOOLEAN(),
               comment='この話に登場せず、プロット・本文に名前が出るだけの人物か。話の確定・プロット補完・枠の生成のたびに、プロット・本文から拾い直す',
               existing_comment='この話に登場せず、プロット・本文に名前が出るだけの人物か。推敲・プロット補完・枠の生成のたびに、プロット・本文から拾い直す',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('episode_character', 'mentioned',
               existing_type=sa.BOOLEAN(),
               comment='この話に登場せず、プロット・本文に名前が出るだけの人物か。推敲・プロット補完・枠の生成のたびに、プロット・本文から拾い直す',
               existing_comment='この話に登場せず、プロット・本文に名前が出るだけの人物か。話の確定・プロット補完・枠の生成のたびに、プロット・本文から拾い直す',
               existing_nullable=False)
    op.create_table('ai_task',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('entrance', sa.VARCHAR(), autoincrement=False, nullable=False, comment='呼ぶ入口(`gui/api/interface.py` の id。例: episode.generate_episode.GenerateEpisode)'),
    sa.Column('args', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='入口に渡す引数(JSON)'),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False, comment='queued / running / done / failed'),
    sa.Column('attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='拾った回数。回したセッションが途中で止まって拾い直すたびに増え、上限を超えたら failed にする'),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='入口の結果(JSON)'),
    sa.Column('error', sa.VARCHAR(), autoincrement=False, nullable=True, comment='落ちた理由'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_task_pkey'))
    )
    op.create_index(op.f('ix_ai_task_status'), 'ai_task', ['status'], unique=False)
    # ### end Alembic commands ###
