"""アイデアの呼び名をidea_recognitionテーブルへ移す

Revision ID: 73050fbddcaf
Revises: 0ace2ac49ad4
Create Date: 2026-09-28 17:51:36.109815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73050fbddcaf'
down_revision: Union[str, Sequence[str], None] = '0ace2ac49ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idea_recognition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True, comment='効く場所。この場所とその配下で効く。空ならどこでも効く'),
    sa.Column('start', sa.BigInteger(), nullable=True, comment='効き始める時刻。空なら始まりを限らない'),
    sa.Column('end', sa.BigInteger(), nullable=True, comment='効き終わる時刻(この時刻からは効かない)。空なら終わりを限らない'),
    sa.Column('name', sa.String(), nullable=False, comment='この場所・時代での作中の呼び名'),
    sa.Column('detail', sa.String(), nullable=True, comment='呼び名についての注釈(作中での受け止め方)'),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idea_recognition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idea_recognition_idea_id'), ['idea_id'], unique=False)

    # 「呼び名の本質」という考え方(idea.alias_of_idea_id で自分自身を指す idea 行として呼び名を持つ)をやめ、
    # idea_recognition の子行として持つ。既存の呼び名 idea 行はここでデータを移し替えてから消す。
    connection = op.get_bind()

    connection.execute(sa.text("""
        INSERT INTO idea_recognition (idea_id, location_id, start, "end", name, detail)
        SELECT alias_of_idea_id, location_id, start, "end", name, text
        FROM idea
        WHERE alias_of_idea_id IS NOT NULL
    """))

    # 呼び名 idea 行を直接指していた中間テーブルは、本質(alias_of_idea_id の指す行)へ付け替える。
    # 既に本質への行があれば(付け替えると重複するので)そちらを残し、呼び名側の行は消す。
    for table, owner_column in (("character_idea", "character_id"),
                                ("episode_idea", "episode_id"),
                                ("event_idea", "event_id")):
        connection.execute(sa.text(f"""
            UPDATE {table}
            SET idea_id = (SELECT alias_of_idea_id FROM idea WHERE idea.id = {table}.idea_id)
            WHERE idea_id IN (SELECT id FROM idea WHERE alias_of_idea_id IS NOT NULL)
              AND NOT EXISTS (
                SELECT 1 FROM {table} AS existing
                WHERE existing.{owner_column} = {table}.{owner_column}
                  AND existing.idea_id = (SELECT alias_of_idea_id FROM idea WHERE idea.id = {table}.idea_id)
              )
        """))
        connection.execute(sa.text(f"""
            DELETE FROM {table}
            WHERE idea_id IN (SELECT id FROM idea WHERE alias_of_idea_id IS NOT NULL)
        """))

    # 呼び名 idea 行に付いていた本文の追記(通常は無いはずだが念のため)も本質へ付け替える。
    connection.execute(sa.text("""
        UPDATE idea_note
        SET idea_id = (SELECT alias_of_idea_id FROM idea WHERE idea.id = idea_note.idea_id)
        WHERE idea_id IN (SELECT id FROM idea WHERE alias_of_idea_id IS NOT NULL)
    """))

    # 呼び名 idea 行を上位に持っていたアイデアも、本質を上位に持つよう付け替える。
    connection.execute(sa.text("""
        UPDATE idea
        SET parent_idea_id = (SELECT alias_of_idea_id FROM idea AS essence WHERE essence.id = idea.parent_idea_id)
        WHERE parent_idea_id IN (SELECT id FROM idea WHERE alias_of_idea_id IS NOT NULL)
    """))

    connection.execute(sa.text("DELETE FROM idea WHERE alias_of_idea_id IS NOT NULL"))

    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idea_alias_of_idea_id'))
        batch_op.drop_constraint(batch_op.f('fk_idea_alias_of_idea_id_idea'), type_='foreignkey')
        batch_op.drop_column('alias_of_idea_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alias_of_idea_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_idea_alias_of_idea_id_idea'), 'idea', ['alias_of_idea_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_idea_alias_of_idea_id'), ['alias_of_idea_id'], unique=False)

    with op.batch_alter_table('idea_recognition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idea_recognition_idea_id'))

    op.drop_table('idea_recognition')
    # ### end Alembic commands ###
