"""アイデアの本文への時代ごとの追記(idea_note)を廃止する

Revision ID: c1141ba5ff4e
Revises: 73050fbddcaf
Create Date: 2026-09-28 20:59:05.531424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1141ba5ff4e'
down_revision: Union[str, Sequence[str], None] = '73050fbddcaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idea_note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idea_note_idea_id'))

    op.drop_table('idea_note')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idea_note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('idea_id', sa.INTEGER(), nullable=False),
    sa.Column('start', sa.BIGINT(), nullable=True),
    sa.Column('end', sa.BIGINT(), nullable=True),
    sa.Column('text', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idea_note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idea_note_idea_id'), ['idea_id'], unique=False)

    # ### end Alembic commands ###
