"""人物の説明をcharacter_historyテーブルへ期間ごとに持つ

Revision ID: cdf2736ad036
Revises: c1141ba5ff4e
Create Date: 2026-09-28 23:58:15.607623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf2736ad036'
down_revision: Union[str, Sequence[str], None] = 'c1141ba5ff4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.BigInteger(), nullable=True, comment='この説明が効き始める時。空なら始まりを限らない'),
    sa.Column('end', sa.BigInteger(), nullable=True, comment='この説明が効き終わる時(この時からは効かない)。空なら終わりを限らない'),
    sa.Column('description', sa.String(), nullable=False, comment='この期間での説明'),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_history_character_id'), ['character_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_history_character_id'))

    op.drop_table('character_history')
    # ### end Alembic commands ###
