"""ミームに承認フラグを足す

Revision ID: f000f08fffa6
Revises: f89e5ad412f2
Create Date: 2026-09-27 08:27:03.406696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f000f08fffa6'
down_revision: Union[str, Sequence[str], None] = 'f89e5ad412f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """confirmed を足す。既にあるミームは使われてきたものとして true で始め、
    以降に自動で抜き出すミームは schema.py の既定値どおり false になる。"""
    with op.batch_alter_table('meme', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'confirmed', sa.Boolean(), nullable=False, server_default=sa.true(),
            comment='ユーザが確かめた考え方として使ってよいか。本文から自動で抜き出した直後は false で、'
                    '人物へ引く・書き込む対象に出ない。週次レビューなどで確かめたら true にする'))
    with op.batch_alter_table('meme', schema=None) as batch_op:
        batch_op.alter_column('confirmed', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meme', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
