"""人物の誕生・死亡列をparametersの行へ移す

Revision ID: a4fe8f13c7ce
Revises: 1d83860536f9
Create Date: 2026-09-27 23:23:17.688145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4fe8f13c7ce'
down_revision: Union[str, Sequence[str], None] = '1d83860536f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 誕生は一番早く作った(たいてい一番早く始まる)行の start へ移す。すでに値があれば
    # (period を先に足していた場合)上書きしない
    op.execute(
        "update character_parameter set start = ("
        "  select c.start from character c where c.id = character_parameter.character_id)"
        "where start is null"
        "  and id = (select min(p.id) from character_parameter p"
        "            where p.character_id = character_parameter.character_id)")
    # 死亡は一番後に始まる行(無ければ一番後に作った行)の end へ移す。死んでいなければ、
    # その行が育ちの途中の区切りとして end を持っていても空にする(死亡と区別が付かなくなるため)
    op.execute(
        "update character_parameter set \"end\" = ("
        "  select c.\"end\" from character c where c.id = character_parameter.character_id)"
        "where id = ("
        "    select p.id from character_parameter p"
        "    where p.character_id = character_parameter.character_id"
        "    order by (p.start is not null) desc, p.start desc, p.id desc limit 1)")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('start')
        batch_op.drop_column('end')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end', sa.BIGINT(), nullable=True))
        batch_op.add_column(sa.Column('start', sa.BIGINT(), nullable=True))

    # ### end Alembic commands ###

    # 一番早く始まる行の start を誕生へ戻す
    op.execute(
        "update character set start = ("
        "  select min(p.start) from character_parameter p where p.character_id = character.id)")
    # 一番後に始まる行(無ければ一番後に作った行)の end を死亡へ戻す
    op.execute(
        "update character set \"end\" = ("
        "  select p.\"end\" from character_parameter p where p.character_id = character.id"
        "  order by (p.start is not null) desc, p.start desc, p.id desc limit 1)")
