"""アイデアの本文に時代ごとの追記を足す

Revision ID: 0ace2ac49ad4
Revises: aba4a26c1fd5
Create Date: 2026-09-27 23:42:24.249312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ace2ac49ad4'
down_revision: Union[str, Sequence[str], None] = 'aba4a26c1fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idea_note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.BigInteger(), nullable=True, comment='この追記が効き始める時。空ならいつでも効く'),
    sa.Column('end', sa.BigInteger(), nullable=True, comment='この追記が効き終わる時(この時刻からは効かない)。空ならずっと効く'),
    sa.Column('text', sa.String(), nullable=False, comment='追記の本文'),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('idea_note', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idea_note_idea_id'), ['idea_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idea_note', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idea_note_idea_id'))

    op.drop_table('idea_note')
    # ### end Alembic commands ###
