"""アイデアの本文を作者だけのものにし_idea_knower_event_idea_character_idea_を消す

Revision ID: 94e049fee804
Revises: 3238387997f9
Create Date: 2026-10-04 00:01:32.328393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e049fee804'
down_revision: Union[str, Sequence[str], None] = '3238387997f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_idea_event_id'), table_name='event_idea')
    op.drop_index(op.f('ix_event_idea_idea_id'), table_name='event_idea')
    op.drop_table('event_idea')
    op.drop_index(op.f('ix_character_idea_character_id'), table_name='character_idea')
    op.drop_index(op.f('ix_character_idea_idea_id'), table_name='character_idea')
    op.drop_table('character_idea')
    op.drop_index(op.f('ix_idea_knower_idea_id'), table_name='idea_knower')
    op.drop_index(op.f('ix_idea_knower_knower_id'), table_name='idea_knower')
    op.drop_index(op.f('ix_idea_knower_location_id'), table_name='idea_knower')
    op.drop_table('idea_knower')
    op.alter_column('idea_history', 'detail',
               existing_type=sa.VARCHAR(),
               comment='作中での受け止め方(作中の人物が、このアイデアについて知っていること)',
               existing_comment='呼び名についての注釈(作中での受け止め方)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('idea_history', 'detail',
               existing_type=sa.VARCHAR(),
               comment='呼び名についての注釈(作中での受け止め方)',
               existing_comment='作中での受け止め方(作中の人物が、このアイデアについて知っていること)',
               existing_nullable=True)
    op.create_table('idea_knower',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idea_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('knower_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='知る人物'),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='知る場所。その時刻にこの場所(配下も含む)に住む人物が知る'),
    sa.Column('start', sa.BIGINT(), autoincrement=False, nullable=True, comment='知った時刻。空なら初めから知っている'),
    sa.CheckConstraint('(knower_id IS NULL) <> (location_id IS NULL)', name=op.f('ck_idea_knower_one_knower')),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], name=op.f('idea_knower_idea_id_fkey')),
    sa.ForeignKeyConstraint(['knower_id'], ['character.id'], name=op.f('idea_knower_knower_id_fkey')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('idea_knower_location_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('idea_knower_pkey')),
    sa.UniqueConstraint('idea_id', 'knower_id', name=op.f('idea_knower_idea_id_knower_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('idea_id', 'location_id', name=op.f('idea_knower_idea_id_location_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_idea_knower_location_id'), 'idea_knower', ['location_id'], unique=False)
    op.create_index(op.f('ix_idea_knower_knower_id'), 'idea_knower', ['knower_id'], unique=False)
    op.create_index(op.f('ix_idea_knower_idea_id'), 'idea_knower', ['idea_id'], unique=False)
    op.create_table('character_idea',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idea_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name=op.f('character_idea_character_id_fkey')),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], name=op.f('character_idea_idea_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('character_idea_pkey')),
    sa.UniqueConstraint('character_id', 'idea_id', name=op.f('character_idea_character_id_idea_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_character_idea_idea_id'), 'character_idea', ['idea_id'], unique=False)
    op.create_index(op.f('ix_character_idea_character_id'), 'character_idea', ['character_id'], unique=False)
    op.create_table('event_idea',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idea_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('event_idea_event_id_fkey')),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], name=op.f('event_idea_idea_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('event_idea_pkey')),
    sa.UniqueConstraint('event_id', 'idea_id', name=op.f('event_idea_event_id_idea_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_event_idea_idea_id'), 'event_idea', ['idea_id'], unique=False)
    op.create_index(op.f('ix_event_idea_event_id'), 'event_idea', ['event_id'], unique=False)
    # ### end Alembic commands ###
