"""作品に一覧の並び順を足す

Revision ID: 1362ea2be0c5
Revises: d3fd5b69efec
Create Date: 2026-10-04 20:13:21.456599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1362ea2be0c5'
down_revision: Union[str, Sequence[str], None] = 'd3fd5b69efec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('display_order', sa.Integer(), nullable=True, comment='作品一覧で同じ親の作品の中の並び。小さいほど上。空の作品は後ろに、一番早い話の順'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'display_order')
    # ### end Alembic commands ###
