/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tables */
        get: operations["tables_api_tables_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tables/{table}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Records */
        get: operations["list_records_api_tables__table__records_get"];
        put?: never;
        /** Create Record */
        post: operations["create_record_api_tables__table__records_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tables/{table}/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Options */
        get: operations["list_options_api_tables__table__options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tables/{table}/records/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Record */
        get: operations["get_record_api_tables__table__records__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Record */
        patch: operations["update_record_api_tables__table__records__record_id__patch"];
        trace?: never;
    };
    "/api/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review Summary */
        get: operations["review_summary_api_review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/{table}/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review Next */
        get: operations["review_next_api_review__table__next_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/{table}/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review Decide */
        post: operations["review_decide_api_review__table___record_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interface": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Entrances
         * @description 入口の一覧。`claude` が立つものは Claude Code の環境でだけ、裏の job として走る
         */
        get: operations["list_entrances_api_interface_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interface/{entrance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Entrance
         * @description 入口を呼ぶ。`claude` を叩く入口(と `background` を立てた呼び出し)は job の id を 202 で返し、結果は `/api/jobs/{id}` で引く
         */
        post: operations["run_entrance_api_interface__entrance_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Maps
         * @description 星ごとの地図(html)。場所の座標・領域から描く
         */
        get: operations["maps_api_maps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maps/{planet_id}.svg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Map Svg */
        get: operations["map_svg_api_maps__planet_id__svg_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Relations
         * @description 人物相関図(html)
         */
        get: operations["relations_api_relations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChildListMeta */
        ChildListMeta: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Columns */
            columns: components["schemas"]["ColumnMeta"][];
        };
        /** ColumnMeta */
        ColumnMeta: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Type
             * @enum {string}
             */
            type: "integer" | "number" | "boolean" | "string" | "stamp" | "json" | "confirm" | "id_list";
            /** Nullable */
            nullable: boolean;
            /** Required */
            required: boolean;
            /**
             * Section
             * @default false
             */
            section: boolean;
            /** Choices */
            choices?: string[] | null;
            /** References */
            references?: string | null;
            /**
             * Readonly
             * @default false
             */
            readonly: boolean;
            /**
             * Create Only
             * @default false
             */
            create_only: boolean;
            /** Comment */
            comment?: string | null;
        };
        /**
         * ConfirmStatus
         * @description アイデア・ミームの `confirmed` 列の値。ユーザが確かめたかを三段で持つ。
         *
         *     - 未確認: 本文から自動で足した直後の候補。検索・生成・人物へ引く対象に出ない
         *     - 承認: ユーザが確かめた。使ってよい
         *     - 非承認: ユーザが退けた。使わないが、同じ語をまた候補に足さないよう行は残す
         * @enum {string}
         */
        ConfirmStatus: "未確認" | "承認" | "非承認";
        /** Decision */
        Decision: {
            decision: components["schemas"]["ConfirmStatus"];
            /** Changes */
            changes?: {
                [key: string]: unknown;
            };
        };
        /** EntranceList */
        EntranceList: {
            /** Entrances */
            entrances: components["schemas"]["EntranceMeta"][];
            /** Claude Available */
            claude_available: boolean;
        };
        /** EntranceMeta */
        EntranceMeta: {
            /** Id */
            id: string;
            /** Area */
            area: string;
            /** Name */
            name: string;
            /** Doc */
            doc: string;
            /** Params */
            params: components["schemas"]["EntranceParam"][];
            /** Claude */
            claude: boolean;
            /** Writes */
            writes: boolean;
        };
        /** EntranceParam */
        EntranceParam: {
            /** Name */
            name: string;
            /** Required */
            required: boolean;
            /** Default */
            default?: unknown;
            /**
             * Annotation
             * @default
             */
            annotation: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** World Dir */
            world_dir: string;
            /** Db Path */
            db_path: string;
        };
        /** JobInfo */
        JobInfo: {
            /** Id */
            id: string;
            /** Entrance */
            entrance: string;
            /** Args */
            args: {
                [key: string]: unknown;
            };
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "failed";
            /** Result */
            result?: unknown;
            /** Error */
            error?: string | null;
            /** Created At */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
        };
        /** JobList */
        JobList: {
            /** Jobs */
            jobs: components["schemas"]["JobInfo"][];
        };
        /** Option */
        Option: {
            /** Id */
            id: number;
            /** Label */
            label: string;
        };
        /** OptionList */
        OptionList: {
            /** Items */
            items: components["schemas"]["Option"][];
        };
        /** RecordList */
        RecordList: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Labels */
            labels?: {
                [key: string]: {
                    [key: string]: string;
                };
            };
        };
        /** RecordResponse */
        RecordResponse: {
            /** Record */
            record: {
                [key: string]: unknown;
            };
            /** Label */
            label: string;
            /** Labels */
            labels?: {
                [key: string]: {
                    [key: string]: string;
                };
            };
            /** Related */
            related?: {
                [key: string]: unknown;
            };
        };
        /** ReviewNext */
        ReviewNext: {
            /** Record */
            record: {
                [key: string]: unknown;
            } | null;
            /** Label */
            label: string | null;
            /** Remaining */
            remaining: number;
            /** Labels */
            labels?: {
                [key: string]: {
                    [key: string]: string;
                };
            };
            /** Related */
            related?: {
                [key: string]: unknown;
            };
        };
        /** ReviewSummary */
        ReviewSummary: {
            /** Tables */
            tables: components["schemas"]["ReviewTable"][];
        };
        /** ReviewTable */
        ReviewTable: {
            /** Table */
            table: string;
            /** Label */
            label: string;
            /** Pending */
            pending: number;
            /** Approved */
            approved: number;
            /** Rejected */
            rejected: number;
        };
        /** RunRequest */
        RunRequest: {
            /** Args */
            args?: {
                [key: string]: unknown;
            };
            /**
             * Background
             * @default false
             */
            background: boolean;
        };
        /** RunResult */
        RunResult: {
            /** Entrance */
            entrance: string;
            /** Result */
            result?: unknown;
        };
        /** TableMeta */
        TableMeta: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /** Label Column */
            label_column: string | null;
            /** Columns */
            columns: components["schemas"]["ColumnMeta"][];
            /** Child Lists */
            child_lists: components["schemas"]["ChildListMeta"][];
            /** Reviewable */
            reviewable: boolean;
            /** Count */
            count: number;
        };
        /** TablesResponse */
        TablesResponse: {
            /** Tables */
            tables: components["schemas"]["TableMeta"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    tables_api_tables_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TablesResponse"];
                };
            };
        };
    };
    list_records_api_tables__table__records_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
                offset?: number;
                order?: string;
            };
            header?: never;
            path: {
                table: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_record_api_tables__table__records_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_options_api_tables__table__options_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
                ids?: number[] | null;
            };
            header?: never;
            path: {
                table: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptionList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_record_api_tables__table__records__record_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table: string;
                record_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_record_api_tables__table__records__record_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table: string;
                record_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_summary_api_review_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSummary"];
                };
            };
        };
    };
    review_next_api_review__table__next_get: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: never;
            path: {
                table: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewNext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_decide_api_review__table___record_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table: string;
                record_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entrances_api_interface_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntranceList"];
                };
            };
        };
    };
    run_entrance_api_interface__entrance_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entrance_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResult"] | components["schemas"]["JobInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobList"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    maps_api_maps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    map_svg_api_maps__planet_id__svg_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planet_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    relations_api_relations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
}
