/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping */
        get: operations["ping_api_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tables */
        get: operations["tables_api_tables_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tables/{table}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Records */
        get: operations["list_records_api_tables__table__records_get"];
        put?: never;
        /** Create Record */
        post: operations["create_record_api_tables__table__records_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tables/{table}/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Options */
        get: operations["list_options_api_tables__table__options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tables/{table}/records/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Record */
        get: operations["get_record_api_tables__table__records__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Record */
        patch: operations["update_record_api_tables__table__records__record_id__patch"];
        trace?: never;
    };
    "/api/interface": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Entrances
         * @description db だけの入口の一覧。claude を叩く入口は出さない(Claude のセッションが自分で呼ぶ)
         */
        get: operations["list_entrances_api_interface_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interface/{entrance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Entrance */
        post: operations["run_entrance_api_interface__entrance_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/steps/{step_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Step
         * @description db の段(`data_access_logic/<領域>/steps.py`)を一つのトランザクションで回す。web のセッション(`web_session/`)が、
         *     流れと AI を自分で持ったまま db に触る所だけを頼む
         */
        post: operations["run_step_api_steps__step_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch
         * @description 同じ時に出た GET をまとめて回す。Lambda は一つの実行環境で一つの要求しか受けないので、画面が並べて呼ぶと
         *     その数だけ実行環境が起き、それぞれがコールドスタートを待つ
         */
        post: operations["batch_api_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Maps
         * @description 星ごとの地図の元データ。画面(`/maps`)が場所の座標・領域から描く
         */
        get: operations["maps_api_maps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maps/{planet_id}.svg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Map Svg */
        get: operations["map_svg_api_maps__planet_id__svg_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/story_route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Story Route
         * @description 作品の話を順に並べ、それぞれを地図に置く位置。地図(`/maps?story=`)が場所の移り変わりを描く
         */
        get: operations["get_story_route_api_story_route_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Relations
         * @description 人物相関図の元データ。画面(`/relations`)が描く
         */
        get: operations["relations_api_relations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/character_locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Character Locations
         * @description 人物ごとの居場所。人物一覧のツリー表示(`/tables/character?view=tree`)が場所ごとに束ねるのに使う
         */
        get: operations["character_locations_api_character_locations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/location_characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Location Characters
         * @description `time` に `location_id` の場所か、その上位の場所にいる人物。話の登場人物の候補を、フォームの場所・時刻で絞るのに使う
         */
        get: operations["location_characters_api_location_characters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Timeline
         * @description 全期間の話。画面(`/timeline`)が時刻の軸に並べる
         */
        get: operations["get_timeline_api_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/previous_episode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Previous Episode
         * @description 作品の中で `before`(時刻)より前の一番後ろの話。`before` が無ければ作品の最後の話。
         *     話を新しく足す画面が、場所・視点・登場人物の初期値を写すのに使う
         */
        get: operations["previous_episode_api_previous_episode_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/episode_neighbors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Episode Neighbors
         * @description 同じ作品の時刻の順で前後の話。話の画面のタイトルの横の移動ボタンが使う
         */
        get: operations["episode_neighbors_api_episode_neighbors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/episode_session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Episode Session
         * @description 話のセッションの行のうち `after_id` より新しい行と、行の総数。画面(`/episode_session`)が 3 秒ごとに引いて増分を足す
         */
        get: operations["episode_session_api_episode_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BatchItem */
        BatchItem: {
            /** Status */
            status: number;
            /** Body */
            body?: unknown;
        };
        /** BatchRequest */
        BatchRequest: {
            /** Paths */
            paths: string[];
        };
        /** BatchResponse */
        BatchResponse: {
            /** Responses */
            responses: components["schemas"]["BatchItem"][];
        };
        /** CharacterLocationsResponse */
        CharacterLocationsResponse: {
            /** Locations */
            locations: {
                [key: string]: number;
            };
        };
        /** ChildListMeta */
        ChildListMeta: {
            /** Name */
            name: string;
            /** Table */
            table: string;
            /** Columns */
            columns: components["schemas"]["ColumnMeta"][];
            /** Comment */
            comment?: string | null;
            /**
             * Display
             * @default table
             * @enum {string}
             */
            display: "table" | "periodic" | "flow";
            /**
             * Knowers
             * @default false
             */
            knowers: boolean;
        };
        /** ColumnMeta */
        ColumnMeta: {
            /** Key */
            key: string;
            /**
             * Type
             * @enum {string}
             */
            type: "integer" | "number" | "boolean" | "string" | "stamp" | "json" | "id_list";
            /** Nullable */
            nullable: boolean;
            /** Required */
            required: boolean;
            /**
             * Section
             * @default false
             */
            section: boolean;
            /**
             * Markdown
             * @default true
             */
            markdown: boolean;
            /**
             * Side
             * @default false
             */
            side: boolean;
            /** Choices */
            choices?: string[] | null;
            /** Default */
            default?: string | null;
            /** References */
            references?: string | null;
            /**
             * Readonly
             * @default false
             */
            readonly: boolean;
            /**
             * Create Only
             * @default false
             */
            create_only: boolean;
            /** Comment */
            comment?: string | null;
        };
        /** EntranceList */
        EntranceList: {
            /** Entrances */
            entrances: components["schemas"]["EntranceMeta"][];
        };
        /** EntranceMeta */
        EntranceMeta: {
            /** Id */
            id: string;
            /** Area */
            area: string;
            /** Name */
            name: string;
            /** Doc */
            doc: string;
            /** Params */
            params: components["schemas"]["EntranceParam"][];
            /** Writes */
            writes: boolean;
        };
        /** EntranceParam */
        EntranceParam: {
            /** Name */
            name: string;
            /** Required */
            required: boolean;
            /** Default */
            default?: unknown;
            /**
             * Annotation
             * @default
             */
            annotation: string;
        };
        /** EpisodeCharacterLink */
        EpisodeCharacterLink: {
            /** Character Id */
            character_id: number;
            /**
             * Mentioned
             * @default false
             */
            mentioned: boolean;
        };
        /**
         * EpisodeNeighbors
         * @description 作品の中の並び(`common_query.episode_order`)で、その話のすぐ前とすぐ後の話。
         */
        EpisodeNeighbors: {
            previous?: components["schemas"]["EpisodeTitle"] | null;
            next?: components["schemas"]["EpisodeTitle"] | null;
        };
        /** EpisodeRecord */
        EpisodeRecord: {
            /** Id */
            id: number;
            /** Story Id */
            story_id: number;
            /** Title */
            title: string;
            /** Synced */
            synced: boolean;
            /** Start */
            start?: string | null;
            /** End */
            end?: string | null;
            /** Viewpoint Character Id */
            viewpoint_character_id?: number | null;
            /** Location Id */
            location_id?: number | null;
            /** Letters */
            letters: number;
            /** Plot Text */
            plot_text: string;
            /** Event Seeded */
            event_seeded: boolean;
            /** Main Text */
            main_text: string;
            /** Character Ids */
            readonly character_ids: number[];
            /**
             * Mentioned Character Ids
             * @description この話に登場せず、プロット・本文に名前が出るだけの人物
             */
            readonly mentioned_character_ids: number[];
        };
        /** EpisodeTitle */
        EpisodeTitle: {
            /** Id */
            id: number;
            /** Start */
            start?: string | null;
            /** Title */
            title: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Dialect */
            dialect: string;
        };
        /** LocationCharactersResponse */
        LocationCharactersResponse: {
            /** Character Ids */
            character_ids: number[];
        };
        /** MapLocation */
        MapLocation: {
            /** Id */
            id: number;
            /** Name */
            name: string | null;
            /** Kind */
            kind: string | null;
            /** Category */
            category: string;
            /** Parent Id */
            parent_id: number | null;
            /** Parent Name */
            parent_name: string | null;
            /** Parent Kind */
            parent_kind: string | null;
            /** Lon */
            lon: number | null;
            /** Lat */
            lat: number | null;
            /** Alt */
            alt: number | null;
            /** Polygon */
            polygon: {
                [key: string]: unknown;
            } | null;
            /** Environment */
            environment: string | null;
            /** Sample Region */
            sample_region: string | null;
            /** Sample Culture */
            sample_culture: string | null;
            /** Sample Era */
            sample_era: string | null;
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
            /** Link */
            link: string;
        };
        /** MapsResponse */
        MapsResponse: {
            /** Planets */
            planets: components["schemas"]["PlanetMap"][];
            /** Categories */
            categories: string[];
            /** Category Colors */
            category_colors: {
                [key: string]: string;
            };
            /** Shape Opacity */
            shape_opacity: {
                [key: string]: number;
            };
            /** Bearings */
            bearings: string[];
        };
        /**
         * Named
         * @description 行を id と名前だけで指す。
         */
        Named: {
            /** Id */
            id: number;
            /** Name */
            name?: string | null;
        };
        /** Option */
        Option: {
            /** Id */
            id: number;
            /** Label */
            label: string;
            /** Parent Id */
            parent_id?: number | null;
            /** Born */
            born?: string | null;
        };
        /** OptionList */
        OptionList: {
            /** Items */
            items: components["schemas"]["Option"][];
        };
        /** Planet */
        Planet: {
            /** Id */
            id: number;
            /** Name */
            name: string | null;
            /** Area */
            area: number | null;
            /** Radius Km */
            radius_km: number | null;
        };
        /** PlanetMap */
        PlanetMap: {
            planet: components["schemas"]["Planet"];
            /** Points */
            points: components["schemas"]["MapLocation"][];
            /** Shapes */
            shapes: components["schemas"]["MapLocation"][];
        };
        /** RecordList */
        RecordList: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Labels */
            labels?: {
                [key: string]: {
                    [key: string]: string;
                };
            };
        };
        /** RecordResponse */
        RecordResponse: {
            /** Record */
            record: {
                [key: string]: unknown;
            };
            /** Label */
            label: string;
            /** Labels */
            labels?: {
                [key: string]: {
                    [key: string]: string;
                };
            };
            /** Related */
            related?: {
                [key: string]: unknown;
            };
        };
        /** Relation */
        Relation: {
            /** Id */
            id: number;
            /** Character 1 Id */
            character_1_id: number;
            /** Character 2 Id */
            character_2_id: number;
            /** Relation */
            relation: string | null;
            /** Start */
            start: number | null;
            /** End */
            end: number | null;
            /** Text */
            text: string;
        };
        /** RelationCharacter */
        RelationCharacter: {
            /** Id */
            id: number;
            /** Name */
            name: string | null;
            /** Kind */
            kind: string | null;
            /** Sex */
            sex: string | null;
            /** Start */
            start: number | null;
            /** End */
            end: number | null;
            /** Link */
            link: string;
        };
        /** RelationsResponse */
        RelationsResponse: {
            /** Characters */
            characters: components["schemas"]["RelationCharacter"][];
            /** Relations */
            relations: components["schemas"]["Relation"][];
            /** Colors */
            colors: string[];
        };
        /** RouteStop */
        RouteStop: {
            /** Episode Id */
            episode_id: number;
            /** Title */
            title: string;
            /** Start */
            start: string | null;
            /** Story Id */
            story_id: number;
            /** Location Id */
            location_id: number | null;
            /** Location Name */
            location_name: string | null;
            /** Placed Id */
            placed_id: number | null;
            /** Placed Name */
            placed_name: string | null;
            /** Planet Id */
            planet_id: number | null;
            /** Lon */
            lon: number | null;
            /** Lat */
            lat: number | null;
        };
        /** RunRequest */
        RunRequest: {
            /** Args */
            args?: {
                [key: string]: unknown;
            };
        };
        /** RunResult */
        RunResult: {
            /** Entrance */
            entrance: string;
            /** Result */
            result?: unknown;
        };
        /** SessionRecord */
        SessionRecord: {
            /** Id */
            id: number;
            /** Episode Id */
            episode_id: number;
            character: components["schemas"]["Named"];
            /** Time */
            time?: string | null;
            /** Request */
            request: string;
            /** Closing */
            closing: boolean;
            /** Thought */
            thought?: string | null;
            /** Action */
            action?: string | null;
            /** Speech */
            speech?: string | null;
            /** Aim */
            aim?: string | null;
        };
        /** SessionSince */
        SessionSince: {
            /** Records */
            records: components["schemas"]["SessionRecord"][];
            /** Count */
            count: number;
        };
        /** StoryRoute */
        StoryRoute: {
            /** Story Id */
            story_id: number;
            /** Story Name */
            story_name: string;
            /** Stops */
            stops: components["schemas"]["RouteStop"][];
        };
        /** TableMeta */
        TableMeta: {
            /** Name */
            name: string;
            /** Label Column */
            label_column: string | null;
            /** Columns */
            columns: components["schemas"]["ColumnMeta"][];
            /** Child Lists */
            child_lists: components["schemas"]["ChildListMeta"][];
            /** Count */
            count: number;
            /**
             * Sort
             * @default id
             */
            sort: string;
            /**
             * Order
             * @default desc
             * @enum {string}
             */
            order: "asc" | "desc";
        };
        /** TablesResponse */
        TablesResponse: {
            /** Tables */
            tables: components["schemas"]["TableMeta"][];
        };
        /** TimelineResponse */
        TimelineResponse: {
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Labels */
            labels?: {
                [key: string]: {
                    [key: string]: string;
                };
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ping_api_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    tables_api_tables_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TablesResponse"];
                };
            };
        };
    };
    list_records_api_tables__table__records_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
                offset?: number;
                sort?: string | null;
                order?: string | null;
            };
            header?: never;
            path: {
                table: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_record_api_tables__table__records_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_options_api_tables__table__options_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
                ids?: number[] | null;
            };
            header?: never;
            path: {
                table: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptionList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_record_api_tables__table__records__record_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table: string;
                record_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_record_api_tables__table__records__record_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                table: string;
                record_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entrances_api_interface_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntranceList"];
                };
            };
        };
    };
    run_entrance_api_interface__entrance_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entrance_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_step_api_steps__step_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                step_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_api_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    maps_api_maps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapsResponse"];
                };
            };
        };
    };
    map_svg_api_maps__planet_id__svg_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planet_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_story_route_api_story_route_get: {
        parameters: {
            query: {
                story_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryRoute"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    relations_api_relations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationsResponse"];
                };
            };
        };
    };
    character_locations_api_character_locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterLocationsResponse"];
                };
            };
        };
    };
    location_characters_api_location_characters_get: {
        parameters: {
            query: {
                location_id: number;
                time: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationCharactersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_timeline_api_timeline_get: {
        parameters: {
            query?: {
                story_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    previous_episode_api_previous_episode_get: {
        parameters: {
            query: {
                story_id: number;
                before?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeRecord"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    episode_neighbors_api_episode_neighbors_get: {
        parameters: {
            query: {
                episode_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EpisodeNeighbors"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    episode_session_api_episode_session_get: {
        parameters: {
            query: {
                episode_id: number;
                after_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSince"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
