// 画面に出す文言はすべてここに置き、ページ・コンポーネントは文言を直書きしない。
// db の値(場所の category など)は文言ではなく値なので、ここには置かない。

const join = (keys: string[]) => keys.join(", ");
const dash = (v: unknown) => (v == null ? "-" : String(v));
const span = (start: unknown, end: unknown) => (start == null && end == null ? "" : `${start ?? ""} – ${end ?? ""}`);
const idMark = (id: unknown) => `#${id}`;
// 行の名前は、どの画面でも id と組にして出す(名前が無ければ id だけ)。JSX では components/NameId が同じ並びで出す
const nameId = (name: unknown, id: unknown) => (name == null || name === "" ? idMark(id) : `${name} ${idMark(id)}`);

export const T = {
  appName: "novel db",
  appDescription: "Data editing GUI for ai-novel-core",
  pageTitle: (kind: string, record?: string | null) => (record ? `${kind} - ${record}` : kind),

  loading: "Loading…",
  openRecord: "Open record",
  close: "Close",
  required: "required",
  none: "(none)",
  select: "Select",
  filter: "Filter",
  noCandidates: "No candidates",
  yes: "Yes",
  no: "No",
  zoom: "Zoom",
  invalidJson: (error: string) => `Invalid JSON: ${error}`,
  cannotReachApi: (error: string) => `Cannot reach API: ${error} (check that uvicorn is running)`,
  signInRequired: "Sign in required.",
  span,
  idMark,
  nameId,

  nav: {
    menu: "Menu",
    endpoints: "Endpoints",
    timeline: "Timeline",
    search: "Jump to a page (type a table or page name)",
    noMatch: "No matching page",
    searchHint: "Ctrl+K: search pages",
  },

  home: {
    title: "Tables",
  },

  list: {
    episodesOf: (story: string) => `Episodes of ${story}`,
    stories: "Stories",
    tree: "Tree",
    list: "List",
    add: "+ Add",
    empty: "(empty)",
    searchPlaceholder: "Search name / text",
    search: "Search",
    removeFilter: "Remove this filter",
    filterBy: (label: string) => `Filter by this ${label}`,
    name: "Name",
    text: "Text",
    prev: "Prev",
    next: "Next",
    range: (from: number, to: number, total: number) => `${from}–${to} of ${total}`,
    selectAll: "Select all on this page",
    select: "Select",
    deleteSelected: (count: number) => `Delete selected (${count})`,
    confirmDeleteSelected: (count: number) => `Delete ${count} selected rows? This cannot be undone.`,
  },

  record: {
    clickToEdit: "Click to edit",
    saved: (keys: string[]) => `Saved (${join(keys)})`,
    changed: (keys: string[]) => `Changed: ${join(keys)}`,
    noChanges: "No changes",
    revert: "Revert",
    saveAndBack: "Save and back",
    save: "Save",
    emptySection: "(empty — click to edit)",
    edit: "Edit",
    expand: "Click to show all",
    collapse: "Click to fold",
    ageAt: "Age",
    ageInYear: (age: number) => `(age ${age})`,
    delete: "Delete",
    confirmDeleteEpisode: (label: string) =>
      `Delete episode "${label}"? Its cast is removed too. Events, ideas and memes taken from its text stay. This cannot be undone.`,
    confirmDeleteIdea: (label: string, childCount: number) =>
      childCount > 0
        ? `"${label}" has ${childCount} child idea${childCount === 1 ? "" : "s"}. They will be detached (moved to root) and then "${label}" will be deleted. Continue?`
        : `Delete idea "${label}"? Its histories are removed too. This cannot be undone.`,
    confirmDeleteSkill: (label: string) =>
      `Delete skill "${label}"? Its histories and who knows them are removed too. This cannot be undone.`,
    deleteFailed: (error: string) => `Could not delete: ${error}`,
    previousEpisode: "◀ Prev",
    nextEpisode: "Next ▶",
    noPreviousEpisode: "No earlier episode in this story",
    noNextEpisode: "No later episode in this story",
    openClaude: "Claude ↗",
    openClaudeHint: "Open a new Claude Code session for this episode in a new tab",
    openSession: "Session",
    openSessionHint: "Watch the turns of this episode's session live",
    openClaudeInteractive: "Interactive ↗",
    openClaudeInteractiveHint: "Open a new Claude Code session in a new tab where you narrate this episode and the characters respond",
    // 初めのメッセージは Claude とスキルに向けるので日本語で書く
    claudePromptWrite: (id: string) => `ep${id}`,
    claudePromptInteractive: (id: string) => `ep${id} in`,
    claudePromptRevise: (label: string) => `スキル revise-episode で、エピソード ${label} を書き直して。直したいところ: `,
  },

  session: {
    title: "Session",
    noEpisode: "Open this page from an episode (?episode=<id>)",
    live: "Live (every second)",
    paused: "Paused",
    pause: "Pause",
    resume: "Resume",
    updatedAt: (time: string) => `Updated ${time}`,
    empty: "No turns yet",
    count: (count: number) => `${count} rows`,
    request: "Request",
    thought: "Thought",
    action: "Action",
    speech: "Speech",
    aim: "Aim",
    waiting: "Waiting for the character…",
    queued: "Queued",
    closing: "Closed",
  },

  create: {
    title: (label: string) => `New ${label}`,
    cancel: "Cancel",
    add: "Add",
  },

  endpoints: {
    title: "Call endpoint",
    area: {
      world: "Read world",
      story: "Stories / episodes",
      randomizer: "Add / edit / delete",
      idea: "Idea staging",
      meme: "Memes",
      review: "Review",
      fact_check: "Fact check",
    } as Record<string, string>,
    writesDb: "writes db",
    running: "Running…",
    run: "Run",
    jsonHint: 'Write dicts and arrays as JSON (e.g. {"id": 3, "kind": "概念"} / [1, 2])',
    searchPlaceholder: "Search endpoints",
    selectOne: "Select an endpoint on the left",
  },

  related: {
    relationGraph: { title: "Relation graph", sub: "Only relations involving this character" },
    skills: { title: "Skills", sub: "Skills this character has" },
    mapCentered: { title: "Map centered here", sub: "Map centered on this location" },
    storyRoute: { title: "Route map", sub: "Locations of the episodes, in story order" },
    episodeRoute: { title: "Route map", sub: "Locations of this story's episodes, with this one selected" },
    storyTimeline: { title: "Timeline", sub: "This story's episodes, centered on its period" },
    episodeList: "Episode list",
    episodeSummary: (episodes: number, letters: number) => `${episodes} episodes / ${letters.toLocaleString()} chars`,
    unsynced: (n: number) => ` / ${n} unsynced`,
  },

  episodeContext: {
    title: "In this episode's time & place",
  },

  episodeCharacters: {
    button: (n: number) => `Characters (${n})`,
    modalTitle: "Characters in this episode",
    none: "(no characters yet)",
  },

  characterSheet: {
    record: "Record",
    at: (time: string | null) => (time ? `At ${time}` : "Parameters (no time limits)"),
    born: "Born",
    died: "Died",
    age: "Age",
    location: "Location",
    noText: "(no text)",
    noHistory: "(no history)",
    undated: "Date undecided",
  },

  storyTree: {
    episodes: (n: number) => `${n} episodes`,
    stories: (n: number) => `${n} stories`,
    noStories: "No stories yet",
    moveToRoot: "Move here to make it a top-level story (no parent)",
    move: "Move",
    editHint: "Reorder with ▲▼ or change a parent. Nothing is saved until you apply.",
    apply: (n: number) => `Apply (${n})`,
    applyFailed: (error: string) => `Could not apply: ${error}`,
    discard: "Cancel",
    confirmDiscard: (n: number) => `Discard ${n} unsaved changes?`,
    changeParent: "Change parent",
    cancelMove: "Cancel",
    moveModeHint: (name: string) => `Changing the parent of "${name}" — click another story to make it the new parent (Esc to cancel)`,
    moveUp: "Move up among its siblings",
    moveDown: "Move down among its siblings",
    collapseAll: "Collapse all",
    addChild: "Add child story",
    addEpisode: "Add episode",
  },

  characterTree: {
    characters: (n: number) => `${n} characters`,
    openLocation: "Open location",
    noCharacters: "No characters yet",
    noLocation: "No location",
    collapseAll: "Collapse all",
  },

  ideaTree: {
    empty: "No ideas yet",
    addChild: "Add child",
    move: "Move",
    cancelMove: "Cancel move",
    moveModeHint: (name: string) => `Moving "${name}" — click another idea to make it the new parent`,
    moveToRoot: "Move here to make it a root idea (no parent)",
    moveFailed: (error: string) => `Could not move: ${error}`,
    collapse: "Collapse",
    expand: "Expand",
    collapseAll: "Collapse all",
    delete: "Delete",
    deleteFailed: (error: string) => `Could not delete: ${error}`,
    previousEpisode: "◀ Prev",
    nextEpisode: "Next ▶",
    noPreviousEpisode: "No earlier episode in this story",
    noNextEpisode: "No later episode in this story",
  },

  picker: {
    count: (n: number) => `${n} selected`,
    done: "Done",
  },

  treeSelect: {
    collapse: "Collapse",
    expand: "Expand",
  },

  childList: {
    removeRow: "Remove this row",
    addRow: "+ Add row",
    close: "Close",
  },

  knowers: {
    label: "knowers",
    add: "+ Add character",
    pickTitle: "Add a character who knows this row",
    remove: "Remove this knower",
    location: "location: ",
    since: (start: string) => `(from ${start})`,
  },

  skills: {
    title: (name: string) => `Skills — ${name}`,
    add: "+ Add skill",
    none: "No skills yet",
    unsaved: "new (not saved)",
    openRecord: "Open this skill's page in a new tab",
    changes: (n: number) => `${n} skill${n === 1 ? "" : "s"} changed`,
    saved: (n: number) => `Saved ${n} skill${n === 1 ? "" : "s"}`,
    failed: (error: string) => `Could not save: ${error}`,
    confirmDiscard: (n: number) => `Discard unsaved changes to ${n} skill${n === 1 ? "" : "s"}?`,
  },

  knowledge: {
    open: "Organize knowledge",
    openDisabled: "Save or revert the changes on this page first",
    title: (name: string) => `Organize knowledge — ${name}`,
    filter: "Filter characters, ideas and places by name or id",
    onlyKnown: "Only what this character knows",
    characters: "Characters",
    ideas: "Ideas",
    places: "Places",
    placeHint: "Rows whose knower is a place are known by whoever lives there (or below it). Check a row to let this character know it without living there, e.g. while passing through or as a secret.",
    livesHere: (place: string) => `known by living in ${place}`,
    home: "(lives here)",
    self: "(self)",
    knownCount: (n: number) => `${n} known`,
    noMatch: "No match",
    pickSource: "Pick a character, an idea or a place on the left to see its rows. Click a row to switch between known and not known",
    noHistories: "No rows",
    skill: (name: string) => `Skill: ${name}`,
    undated: "undated",
    date: (stamp: string) => stamp.split(" ")[0],
    anywhere: "anywhere",
    adding: "will know",
    removing: "will forget",
    retiming: "new time",
    knownSince: "Known since (empty: from the beginning)",
    defaultSince: "Known since, for newly checked rows",
    changes: (n: number) => `${n} change${n === 1 ? "" : "s"}`,
    undo: "Undo this change",
    confirmDiscard: (n: number) => `Discard ${n} unsaved change${n === 1 ? "" : "s"}?`,
    saved: (n: number) => `Saved ${n} change${n === 1 ? "" : "s"}`,
    failed: (error: string) => `Could not save: ${error}`,
  },

  maps: {
    title: "Location map",
    centeredOn: (name: string) => `Map centered on ${name}`,
    fullMap: "Full map",
    cannotPlace: (id: number) => `Location id=${id} has neither coordinates nor a polygon, so it cannot be placed on the map. `,
    nonePlaceable: "No location has coordinates or a polygon.",
    radius: (km: number) => `radius ≈ ${Math.round(km).toLocaleString()} km, 1° latitude ≈ ${Math.round((km * Math.PI) / 180).toLocaleString()} km`,
    radiusUnknown: "radius unknown (no area)",
    nameKind: (name: unknown, kind: unknown) => `${name} (${kind ?? ""})`,
    parent: (name: unknown) => `parent: ${dash(name)}`,
    polygonVertices: (n: number) => `polygon: ${n} vertices`,
    environment: (e: string) => `environment: ${e}`,
    lonLatAlt: (lon: number, lat: number, alt: unknown) => `lon ${lon} / lat ${lat} / alt ${dash(alt)}`,
    period: (start: unknown, end: unknown) => `period: ${span(start, end)}`,
    hintClick: "Click a point to show distance and bearing to the other locations. Double-click to open its record.",
    hintCounts: (points: number, shapes: number) => `${points} locations with coordinates, ${shapes} with a polygon. Polygons are drawn as faint areas.`,
    coordinates: "Coordinates",
    environmentDt: "Environment",
    columns: { location: "Location", bearing: "Bearing", distance: "Distance", elevationDiff: "Elevation diff", order: "#", episode: "Episode" },
    sameCoordinates: "same coordinates",
    aboutDegrees: (deg: number) => `≈ ${deg.toFixed(1)}°`,
    aboutKm: (km: number) => `≈ ${km.toLocaleString()} km`,
    altDiffUnknown: "elevation diff unknown",
    sameAltitude: "same altitude",
    altDiff: (up: boolean, m: number) => `${up ? "up" : "down"} ${m.toLocaleString()} m`,
    routeOf: (story: string) => `Route of ${story}`,
    routeCounts: (placed: number, total: number) => `${placed} of ${total} episodes placed on the map. Numbers follow the story order; consecutive episodes in one place share a number.`,
    routeOtherPlanet: (planet: string) => `on ${planet}`,
    routeUnplaced: "no location on the map",
    routeNoLocation: "no location",
    routePlacedAt: (name: string) => `placed at ${name}`,
    routeNone: "No episode of this story has a location on the map.",
  },

  timeline: {
    title: "Timeline",
    centeredOn: (at: string) => `Timeline around ${at}`,
    center: "Center",
    scale: "Scale",
    years: (n: number) => `${n} year${n === 1 ? "" : "s"}`,
    fewerYears: "Show one year less down the screen (zoom in)",
    moreYears: "Show one year more down the screen (zoom out)",
    squeeze: "Squeeze empty stretches",
    earlier: "▲ Earlier",
    later: "Later ▼",
    story: "Story",
    edit: "Edit",
    editHint: "Drag cards up or down to change their time, or sideways to another story column. Nothing is saved until you apply.",
    apply: (n: number) => `Apply (${n})`,
    applied: (n: number) => `Saved ${n} episode${n === 1 ? "" : "s"}`,
    applyFailed: (error: string) => `Could not apply: ${error}`,
    discard: "Cancel",
    confirmDiscard: (n: number) => `Discard ${n} unsaved changes?`,
    was: (start: string, story: string) => `before: ${start} / ${story}`,
    gap: "No episodes (squeezed)",
    skipped: (days: number) =>
      days >= 365 ? `${Math.round(days / 365.2)}y` : days >= 61 ? `${Math.round(days / 30.4)}mo` : `${Math.round(days)}d`,
    openInNewTab: "Open in new tab",
    newEpisode: "New episode",
    newEpisodeIn: (story: string) => `Story: ${story}`,
    newEpisodeStart: "Start",
    newEpisodeTitle: "title",
    newEpisodePlot: "plot_text",
    newEpisodeNoStory: "Pick a story row to add here, or open the full form",
    addEpisode: "Add",
  },

  episodeSheet: {
    relation: (partner: string, relation: string) => `→ ${partner}: ${relation}`,
    noRelations: "(no relations)",
    toggleRelations: (open: boolean) => (open ? "Hide relations ▴" : "Show relations ▾"),
  },

  stamp: {
    pick: "Pick date & time",
    pickIcon: "📅",
    clear: "Clear",
    set: "Set",
    hour: "H",
    minute: "M",
    second: "S",
    month: (m: number) => `${m}`,
  },

  relations: {
    title: "Character relations",
    of: (name: string) => `Relations of ${name}`,
    fullGraph: "Full graph",
    noKind: "(no kind)",
    year: "Year",
    allTime: "All time",
    relayout: "Re-layout",
    noCharacters: "No characters.",
    noCharacter: (id: number) => `No character with id=${id}.`,
    hintClick: "Click a character to show their relations, or an arrow to show the relation text. Double-click to open the record. Drag characters to move them.",
    hintCounts: (chars: number, rels: number, year: number | null) =>
      `${chars} characters, ${rels} relations${year == null ? "" : ` (active in year ${year})`}. Arrows point from character_1_id to character_2_id.`,
    columns: { subject: "Subject", relation: "Relation", target: "Target", period: "Period" },
    sex: "Sex",
    period: "Period",
    relation: "Relation",
    noRelations: "No relations.",
    noText: "No text.",
    nameKind: (name: unknown, kind: unknown) => `${name} (${kind ?? ""})`,
    sexOf: (sex: string) => `sex: ${sex}`,
    periodOf: (span: string) => `period: ${span}`,
    arrow: (from: string, to: string, relation: string | null) => `${from} → ${to}: ${relation ?? ""}`,
  },
} as const;
