"""話の本文を episode_text へ分ける

Revision ID: c207213edd7f
Revises: 1bdb6a716b4b
Create Date: 2026-09-26 21:59:41.592066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c207213edd7f'
down_revision: Union[str, Sequence[str], None] = '1bdb6a716b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episode_text',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('letters', sa.Integer(), nullable=False, comment='字数。本文から数える'),
    sa.Column('model', sa.String(), nullable=True, comment='本文を書いたモデル。空なら不明(手で書いた本文など)'),
    sa.Column('effort', sa.String(), nullable=True, comment='本文を書いたときの effort。空なら不明(手で書いた本文など)'),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('directory_path', sa.String(), nullable=True, comment='import,export時の配置先。worlds/{table}/ からの相対ディレクトリパス。空ならテーブル直下に置く'),
    sa.Column('filename', sa.String(), nullable=True, comment='import,export時のファイル名(id・拡張子を除いた部分)。空なら {id}.md。テーブルが持つ name 等の列とは別物'),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('episode_text', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_episode_text_episode_id'), ['episode_id'], unique=True)

    # 本文のある話だけ本文を移す。話の md は作品の md の下へ入れ子で置くので、置き場所は空にする
    op.execute(
        "INSERT INTO episode_text (episode_id, letters, text) "
        "SELECT id, length(text), text FROM episode WHERE text <> ''")
    op.execute("UPDATE episode SET directory_path = NULL")

    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.drop_column('text')
        batch_op.drop_column('letters')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('letters', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('text', sa.VARCHAR(), nullable=False, server_default=''))

    op.execute(
        "UPDATE episode SET "
        "text = coalesce((SELECT text FROM episode_text WHERE episode_id = episode.id), ''), "
        "letters = coalesce((SELECT letters FROM episode_text WHERE episode_id = episode.id), 0)")

    with op.batch_alter_table('episode_text', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_episode_text_episode_id'))

    op.drop_table('episode_text')
    # ### end Alembic commands ###
