"""本文と来歴に公開度と知る人を足し、アイデアの来歴と話のセッションの表を足す

本文(人物・アイデア)は既定で公開、来歴は既定で非公開にする。非公開のものは知る人(`*_knower`)に入った人物だけが知る。
今ある人物の来歴は非公開になるので、本人だけを知る人に入れる。人物は自分の本文を知る人にも入れる(`Character` を作るときと同じ)。

Revision ID: 408a7902090d
Revises: d92b78b172bf
Create Date: 2026-10-03 07:22:16.345655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '408a7902090d'
down_revision: Union[str, Sequence[str], None] = 'd92b78b172bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_knower',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False, comment='知られる人物'),
    sa.Column('knower_id', sa.Integer(), nullable=False, comment='知る人物'),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['knower_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'knower_id')
    )
    op.create_index(op.f('ix_character_knower_character_id'), 'character_knower', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_knower_knower_id'), 'character_knower', ['knower_id'], unique=False)
    op.create_table('character_history_knower',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_history_id', sa.Integer(), nullable=False),
    sa.Column('knower_id', sa.Integer(), nullable=False, comment='知る人物'),
    sa.ForeignKeyConstraint(['character_history_id'], ['character_history.id'], ),
    sa.ForeignKeyConstraint(['knower_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_history_id', 'knower_id')
    )
    op.create_index(op.f('ix_character_history_knower_character_history_id'), 'character_history_knower', ['character_history_id'], unique=False)
    op.create_index(op.f('ix_character_history_knower_knower_id'), 'character_history_knower', ['knower_id'], unique=False)
    op.create_table('idea_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=True, comment='起きた年(この来歴が効き始める年)。空なら年が決まっていない(話・出来事には渡さない)'),
    sa.Column('visibility', sa.Enum('public', 'private', name='visibility', native_enum=False, length=16), server_default='private', nullable=False, comment='公開度。public は誰でも知りうる。private は知る人(idea_history_knower)に入った人物だけが知る'),
    sa.Column('description', sa.String(), nullable=False, comment='来歴'),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idea_history_idea_id'), 'idea_history', ['idea_id'], unique=False)
    op.create_table('idea_knower',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('knower_id', sa.Integer(), nullable=False, comment='知る人物'),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], ),
    sa.ForeignKeyConstraint(['knower_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idea_id', 'knower_id')
    )
    op.create_index(op.f('ix_idea_knower_idea_id'), 'idea_knower', ['idea_id'], unique=False)
    op.create_index(op.f('ix_idea_knower_knower_id'), 'idea_knower', ['knower_id'], unique=False)
    op.create_table('episode_character_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False, comment='この手番で動く人物'),
    sa.Column('time', sa.BigInteger(), nullable=True, comment='この手番の作中の時刻'),
    sa.Column('request', sa.String(), nullable=False, comment='語り部の要求。前の手番から、その人物に見える・聞こえるようになったこと(状況の差分)と、この手番で求めること'),
    sa.Column('closing', sa.Boolean(), nullable=False, comment='話が終わった合図。人物役はこの行を読んだら止まる'),
    sa.Column('thought', sa.String(), nullable=True, comment='人物の内心(言葉にしない思い)'),
    sa.Column('action', sa.String(), nullable=True, comment='人物の行動(外から見える動き)。空ならまだ動いていない'),
    sa.Column('speech', sa.String(), nullable=True, comment='人物のセリフ'),
    sa.Column('aim', sa.String(), nullable=True, comment='この手番での人物の狙い'),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episode_character_session_character_id'), 'episode_character_session', ['character_id'], unique=False)
    op.create_index(op.f('ix_episode_character_session_episode_id'), 'episode_character_session', ['episode_id'], unique=False)
    op.create_table('idea_history_knower',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idea_history_id', sa.Integer(), nullable=False),
    sa.Column('knower_id', sa.Integer(), nullable=False, comment='知る人物'),
    sa.ForeignKeyConstraint(['idea_history_id'], ['idea_history.id'], ),
    sa.ForeignKeyConstraint(['knower_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idea_history_id', 'knower_id')
    )
    op.create_index(op.f('ix_idea_history_knower_idea_history_id'), 'idea_history_knower', ['idea_history_id'], unique=False)
    op.create_index(op.f('ix_idea_history_knower_knower_id'), 'idea_history_knower', ['knower_id'], unique=False)
    op.add_column('character', sa.Column('visibility', sa.Enum('public', 'private', name='visibility', native_enum=False, length=16), server_default='public', nullable=False, comment='公開度。public は誰でも知りうる。private は知る人(character_knower)に入った人物だけが知る'))
    op.add_column('character_history', sa.Column('visibility', sa.Enum('public', 'private', name='visibility', native_enum=False, length=16), server_default='private', nullable=False, comment='公開度。public は誰でも知りうる。private は知る人(character_history_knower)に入った人物だけが知る'))
    op.add_column('idea', sa.Column('visibility', sa.Enum('public', 'private', name='visibility', native_enum=False, length=16), server_default='public', nullable=False, comment='公開度。public は誰でも知りうる。private は知る人(idea_knower)に入った人物だけが知る'))
    # ### end Alembic commands ###
    op.execute("INSERT INTO character_history_knower (character_history_id, knower_id) "
               "SELECT id, character_id FROM character_history")
    op.execute("INSERT INTO character_knower (character_id, knower_id) SELECT id, id FROM character")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idea', 'visibility')
    op.drop_column('character_history', 'visibility')
    op.drop_column('character', 'visibility')
    op.drop_index(op.f('ix_idea_history_knower_knower_id'), table_name='idea_history_knower')
    op.drop_index(op.f('ix_idea_history_knower_idea_history_id'), table_name='idea_history_knower')
    op.drop_table('idea_history_knower')
    op.drop_index(op.f('ix_episode_character_session_episode_id'), table_name='episode_character_session')
    op.drop_index(op.f('ix_episode_character_session_character_id'), table_name='episode_character_session')
    op.drop_table('episode_character_session')
    op.drop_index(op.f('ix_idea_knower_knower_id'), table_name='idea_knower')
    op.drop_index(op.f('ix_idea_knower_idea_id'), table_name='idea_knower')
    op.drop_table('idea_knower')
    op.drop_index(op.f('ix_idea_history_idea_id'), table_name='idea_history')
    op.drop_table('idea_history')
    op.drop_index(op.f('ix_character_history_knower_knower_id'), table_name='character_history_knower')
    op.drop_index(op.f('ix_character_history_knower_character_history_id'), table_name='character_history_knower')
    op.drop_table('character_history_knower')
    op.drop_index(op.f('ix_character_knower_knower_id'), table_name='character_knower')
    op.drop_index(op.f('ix_character_knower_character_id'), table_name='character_knower')
    op.drop_table('character_knower')
    # ### end Alembic commands ###
