"""知る相手と知った時刻を持たせ、人物の本文を列に分け、アイデアの来歴と話のセッションの表を足す

人物・アイデアの本文と来歴は、知る相手(`*_knower`。人物か場所)に当たる人物だけが知る。今ある人物の本文と来歴は、本人だけを知る相手にする
(人物は作るときに本人が自分の本文を知る相手に入るのと同じ)。アイデアは、効く場所と期間に住む人物が行が無くても知るので、行を足さない。
人物の本文の `# meme` / `# 行動原理` / `# plot` の節は、それぞれ meme / principle / plot の列へ移す。ほかの節は text に残す。
外見(appearance)は、見出しだけでは秘密と見分けられないので移さず、空のままにする。

Revision ID: 1a43c1c5f4fd
Revises: d92b78b172bf
Create Date: 2026-10-03 07:39:41.512933

"""
from typing import Sequence, Union

import re

from alembic import op
import sqlalchemy as sa

# 本文の一段目の見出しのうち、列へ移すもの
_COLUMNS = {"meme": "meme", "行動原理": "principle", "plot": "plot"}
_HEADING = re.compile(r"^#(?!#)[ \t]*(.+?)[ \t]*$")


def _split(text: str) -> dict[str, str | None]:
    kept: list[str] = []
    taken: dict[str, list[str]] = {}
    column = None
    for line in text.splitlines():
        heading = _HEADING.match(line)
        if heading:
            column = _COLUMNS.get(heading.group(1))
            if column:
                taken.setdefault(column, [])
                continue
        (taken[column] if column else kept).append(line)
    split = {name: "\n".join(lines).strip() or None for name, lines in taken.items()}
    return {"text": "\n".join(kept).strip() or None, **split}


# revision identifiers, used by Alembic.
revision: str = '1a43c1c5f4fd'
down_revision: Union[str, Sequence[str], None] = 'd92b78b172bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_knower',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False, comment='知られる人物'),
    sa.Column('knower_id', sa.Integer(), nullable=True, comment='知る人物'),
    sa.Column('location_id', sa.Integer(), nullable=True, comment='知る場所。その時刻にこの場所(配下も含む)に住む人物が知る'),
    sa.Column('start', sa.BigInteger(), nullable=True, comment='知った時刻。空なら初めから知っている'),
    sa.CheckConstraint('(knower_id IS NULL) <> (location_id IS NULL)', name='ck_character_knower_one_knower'),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['knower_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'knower_id'),
    sa.UniqueConstraint('character_id', 'location_id')
    )
    op.create_index(op.f('ix_character_knower_character_id'), 'character_knower', ['character_id'], unique=False)
    op.create_index(op.f('ix_character_knower_knower_id'), 'character_knower', ['knower_id'], unique=False)
    op.create_index(op.f('ix_character_knower_location_id'), 'character_knower', ['location_id'], unique=False)
    op.create_table('character_history_knower',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_history_id', sa.Integer(), nullable=False),
    sa.Column('knower_id', sa.Integer(), nullable=True, comment='知る人物'),
    sa.Column('location_id', sa.Integer(), nullable=True, comment='知る場所。その時刻にこの場所(配下も含む)に住む人物が知る'),
    sa.Column('start', sa.BigInteger(), nullable=True, comment='知った時刻。空なら初めから知っている'),
    sa.CheckConstraint('(knower_id IS NULL) <> (location_id IS NULL)', name='ck_character_history_knower_one_knower'),
    sa.ForeignKeyConstraint(['character_history_id'], ['character_history.id'], ),
    sa.ForeignKeyConstraint(['knower_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_history_id', 'knower_id'),
    sa.UniqueConstraint('character_history_id', 'location_id')
    )
    op.create_index(op.f('ix_character_history_knower_character_history_id'), 'character_history_knower', ['character_history_id'], unique=False)
    op.create_index(op.f('ix_character_history_knower_knower_id'), 'character_history_knower', ['knower_id'], unique=False)
    op.create_index(op.f('ix_character_history_knower_location_id'), 'character_history_knower', ['location_id'], unique=False)
    op.create_table('idea_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=True, comment='起きた年(この来歴が効き始める年)。空なら年が決まっていない(話・出来事には渡さない)'),
    sa.Column('description', sa.String(), nullable=False, comment='来歴'),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idea_history_idea_id'), 'idea_history', ['idea_id'], unique=False)
    op.create_table('idea_knower',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('knower_id', sa.Integer(), nullable=True, comment='知る人物'),
    sa.Column('location_id', sa.Integer(), nullable=True, comment='知る場所。その時刻にこの場所(配下も含む)に住む人物が知る'),
    sa.Column('start', sa.BigInteger(), nullable=True, comment='知った時刻。空なら初めから知っている'),
    sa.CheckConstraint('(knower_id IS NULL) <> (location_id IS NULL)', name='ck_idea_knower_one_knower'),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], ),
    sa.ForeignKeyConstraint(['knower_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idea_id', 'knower_id'),
    sa.UniqueConstraint('idea_id', 'location_id')
    )
    op.create_index(op.f('ix_idea_knower_idea_id'), 'idea_knower', ['idea_id'], unique=False)
    op.create_index(op.f('ix_idea_knower_knower_id'), 'idea_knower', ['knower_id'], unique=False)
    op.create_index(op.f('ix_idea_knower_location_id'), 'idea_knower', ['location_id'], unique=False)
    op.create_table('episode_character_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False, comment='この手番で動く人物'),
    sa.Column('time', sa.BigInteger(), nullable=True, comment='この手番の作中の時刻'),
    sa.Column('request', sa.String(), nullable=False, comment='語り部の要求。前の手番から、その人物に見える・聞こえるようになったこと(状況の差分)と、この手番で求めること'),
    sa.Column('closing', sa.Boolean(), nullable=False, comment='話が終わった合図。人物役はこの行を読んだら止まる'),
    sa.Column('thought', sa.String(), nullable=True, comment='人物の内心(言葉にしない思い)'),
    sa.Column('action', sa.String(), nullable=True, comment='人物の行動(外から見える動き)。空ならまだ動いていない'),
    sa.Column('speech', sa.String(), nullable=True, comment='人物のセリフ'),
    sa.Column('aim', sa.String(), nullable=True, comment='この手番での人物の狙い'),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['episode_id'], ['episode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episode_character_session_character_id'), 'episode_character_session', ['character_id'], unique=False)
    op.create_index(op.f('ix_episode_character_session_episode_id'), 'episode_character_session', ['episode_id'], unique=False)
    op.create_table('idea_history_knower',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idea_history_id', sa.Integer(), nullable=False),
    sa.Column('knower_id', sa.Integer(), nullable=True, comment='知る人物'),
    sa.Column('location_id', sa.Integer(), nullable=True, comment='知る場所。その時刻にこの場所(配下も含む)に住む人物が知る'),
    sa.Column('start', sa.BigInteger(), nullable=True, comment='知った時刻。空なら初めから知っている'),
    sa.CheckConstraint('(knower_id IS NULL) <> (location_id IS NULL)', name='ck_idea_history_knower_one_knower'),
    sa.ForeignKeyConstraint(['idea_history_id'], ['idea_history.id'], ),
    sa.ForeignKeyConstraint(['knower_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idea_history_id', 'knower_id'),
    sa.UniqueConstraint('idea_history_id', 'location_id')
    )
    op.create_index(op.f('ix_idea_history_knower_idea_history_id'), 'idea_history_knower', ['idea_history_id'], unique=False)
    op.create_index(op.f('ix_idea_history_knower_knower_id'), 'idea_history_knower', ['knower_id'], unique=False)
    op.create_index(op.f('ix_idea_history_knower_location_id'), 'idea_history_knower', ['location_id'], unique=False)
    op.add_column('character', sa.Column('appearance', sa.String(), nullable=True, comment='外見。見て分かること(顔立ち・体つき・身なり・目に見える持ち物)'))
    op.add_column('character', sa.Column('meme', sa.String(), nullable=True, comment='持つミーム。`- <古今表裏>: <文面>` の箇条書き'))
    op.add_column('character', sa.Column('principle', sa.String(), nullable=True, comment='行動原理(ミームどうしの関係と、その人物を動かすもの)'))
    op.add_column('character', sa.Column('plot', sa.String(), nullable=True, comment='その人物について作者が進めたい筋書き'))
    op.alter_column('character', 'text',
               existing_type=sa.VARCHAR(),
               comment='人物の芯(経歴・立場・性格の説明)。いつの話・出来事にも渡す',
               existing_comment='人物の芯(説明・meme・行動原理・plot)。いつの話・出来事にも渡す',
               existing_nullable=True)
    # ### end Alembic commands ###
    bind = op.get_bind()
    for id_, text in bind.execute(sa.text("SELECT id, text FROM character WHERE text IS NOT NULL")).all():
        split = _split(text)
        if set(split) == {"text"}:
            continue
        bind.execute(sa.text("UPDATE character SET text = :text, meme = :meme, principle = :principle, plot = :plot "
                             "WHERE id = :id"),
                     {"id": id_, "meme": None, "principle": None, "plot": None, **split})
    op.execute("INSERT INTO character_knower (character_id, knower_id) SELECT id, id FROM character")
    op.execute("INSERT INTO character_history_knower (character_history_id, knower_id) "
               "SELECT id, character_id FROM character_history")


def downgrade() -> None:
    bind = op.get_bind()
    rows = bind.execute(sa.text("SELECT id, text, meme, principle, plot FROM character "
                                "WHERE meme IS NOT NULL OR principle IS NOT NULL OR plot IS NOT NULL")).all()
    for id_, text, meme, principle, plot in rows:
        parts = [text or "", *(f"# {heading}\n{value}" for heading, value in
                               (("meme", meme), ("行動原理", principle), ("plot", plot)) if value)]
        bind.execute(sa.text("UPDATE character SET text = :text WHERE id = :id"),
                     {"id": id_, "text": "\n\n".join(part for part in parts if part)})
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character', 'text',
               existing_type=sa.VARCHAR(),
               comment='人物の芯(説明・meme・行動原理・plot)。いつの話・出来事にも渡す',
               existing_comment='人物の芯(経歴・立場・性格の説明)。いつの話・出来事にも渡す',
               existing_nullable=True)
    op.drop_column('character', 'plot')
    op.drop_column('character', 'principle')
    op.drop_column('character', 'meme')
    op.drop_column('character', 'appearance')
    op.drop_index(op.f('ix_idea_history_knower_location_id'), table_name='idea_history_knower')
    op.drop_index(op.f('ix_idea_history_knower_knower_id'), table_name='idea_history_knower')
    op.drop_index(op.f('ix_idea_history_knower_idea_history_id'), table_name='idea_history_knower')
    op.drop_table('idea_history_knower')
    op.drop_index(op.f('ix_episode_character_session_episode_id'), table_name='episode_character_session')
    op.drop_index(op.f('ix_episode_character_session_character_id'), table_name='episode_character_session')
    op.drop_table('episode_character_session')
    op.drop_index(op.f('ix_idea_knower_location_id'), table_name='idea_knower')
    op.drop_index(op.f('ix_idea_knower_knower_id'), table_name='idea_knower')
    op.drop_index(op.f('ix_idea_knower_idea_id'), table_name='idea_knower')
    op.drop_table('idea_knower')
    op.drop_index(op.f('ix_idea_history_idea_id'), table_name='idea_history')
    op.drop_table('idea_history')
    op.drop_index(op.f('ix_character_history_knower_location_id'), table_name='character_history_knower')
    op.drop_index(op.f('ix_character_history_knower_knower_id'), table_name='character_history_knower')
    op.drop_index(op.f('ix_character_history_knower_character_history_id'), table_name='character_history_knower')
    op.drop_table('character_history_knower')
    op.drop_index(op.f('ix_character_knower_location_id'), table_name='character_knower')
    op.drop_index(op.f('ix_character_knower_knower_id'), table_name='character_knower')
    op.drop_index(op.f('ix_character_knower_character_id'), table_name='character_knower')
    op.drop_table('character_knower')
    # ### end Alembic commands ###
