"""作品の start と end を消す

作品の時期は話(episode)の時刻で決まるので、作品に別に持たない。並べるときは作品と子孫の作品の一番早い話の順にし、
時刻を渡さずに作品の材料を読むときは作品の最後の話の時刻を使う。

Revision ID: d92b78b172bf
Revises: 3b9c1e5d7a42
Create Date: 2026-10-03 08:17:59.839674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd92b78b172bf'
down_revision: Union[str, Sequence[str], None] = '3b9c1e5d7a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'start')
    op.drop_column('story', 'end')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('end', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('story', sa.Column('start', sa.BIGINT(), autoincrement=False, nullable=True, comment='立つ年'))
    # ### end Alembic commands ###
