"""人物の関係の来歴を_character_relation_history_に年ごとに持つ

Revision ID: 3238387997f9
Revises: e33f37641d9c
Create Date: 2026-10-03 11:38:42.138101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3238387997f9'
down_revision: Union[str, Sequence[str], None] = 'e33f37641d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_relation_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_relation_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=True, comment='起きた年(この来歴が効き始める年)。空なら年が決まっていない(話・人物役には渡さない)'),
    sa.Column('description', sa.String(), nullable=False, comment='来歴'),
    sa.ForeignKeyConstraint(['character_relation_id'], ['character_relation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_relation_history_character_relation_id'), 'character_relation_history', ['character_relation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_relation_history_character_relation_id'), table_name='character_relation_history')
    op.drop_table('character_relation_history')
    # ### end Alembic commands ###
