"""話のセッションにイベントの行と環境の変化の列を足す

イベントの行は人物も要求も持たないので、character_id と request を空にできるようにする。

Revision ID: 9e5d8c7afaad
Revises: 94e049fee804
Create Date: 2026-10-03 23:20:39.231263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5d8c7afaad'
down_revision: Union[str, Sequence[str], None] = '94e049fee804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode_character_session', sa.Column('is_event', sa.Boolean(), server_default=sa.false(), nullable=False, comment='語り部が場面・環境を送るイベントの行。人物は空で、手番に数えない'))
    op.add_column('episode_character_session', sa.Column('event', sa.String(), nullable=True, comment='環境への変化。イベントの行は語り部が送る場面・環境、人物の行はその人物の行動が起こした変化'))
    op.alter_column('episode_character_session', 'character_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='この手番で動く人物。イベントの行は空',
               existing_comment='この手番で動く人物')
    op.alter_column('episode_character_session', 'request',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='語り部の要求。前の手番から、その人物に見える・聞こえるようになったこと(状況の差分)と、この手番で求めること。イベントの行は空',
               existing_comment='語り部の要求。前の手番から、その人物に見える・聞こえるようになったこと(状況の差分)と、この手番で求めること')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # イベントの行は人物も要求も持たず、NOT NULL に戻せないので消す
    op.execute('DELETE FROM episode_character_session WHERE is_event')
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('episode_character_session', 'request',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment='語り部の要求。前の手番から、その人物に見える・聞こえるようになったこと(状況の差分)と、この手番で求めること',
               existing_comment='語り部の要求。前の手番から、その人物に見える・聞こえるようになったこと(状況の差分)と、この手番で求めること。イベントの行は空')
    op.alter_column('episode_character_session', 'character_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='この手番で動く人物',
               existing_comment='この手番で動く人物。イベントの行は空')
    op.drop_column('episode_character_session', 'event')
    op.drop_column('episode_character_session', 'is_event')
    # ### end Alembic commands ###
