"""アイデアの履歴の行に非公開(private)を足す

Revision ID: 7834713286be
Revises: 94e049fee804
Create Date: 2026-10-03 23:37:06.292121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7834713286be'
down_revision: Union[str, Sequence[str], None] = '94e049fee804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idea_history', sa.Column('private', sa.Boolean(), server_default='false', nullable=False, comment='非公開。効く場所・期間に住む人物も知らず、知る相手だけが知る。作中の呼び名にも使わない'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idea_history', 'private')
    # ### end Alembic commands ###
