"""人物の芯を知る相手 character_knower を消し 芯は本人と関係のある人物が知る

Revision ID: 8cedfefec3d8
Revises: 7c4e1a9b3f62
Create Date: 2026-10-05 01:06:36.482864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cedfefec3d8'
down_revision: Union[str, Sequence[str], None] = '7c4e1a9b3f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_knower_character_id'), table_name='character_knower')
    op.drop_index(op.f('ix_character_knower_knower_id'), table_name='character_knower')
    op.drop_index(op.f('ix_character_knower_location_id'), table_name='character_knower')
    op.drop_table('character_knower')
    op.alter_column('character', 'text',
               existing_type=sa.VARCHAR(),
               comment='人物の芯(経歴・立場・性格の説明)。いつの話・出来事にも渡す。本人と関係のある人物が知る',
               existing_comment='人物の芯(経歴・立場・性格の説明)。いつの話・出来事にも渡す',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character', 'text',
               existing_type=sa.VARCHAR(),
               comment='人物の芯(経歴・立場・性格の説明)。いつの話・出来事にも渡す',
               existing_comment='人物の芯(経歴・立場・性格の説明)。いつの話・出来事にも渡す。本人と関係のある人物が知る',
               existing_nullable=True)
    op.create_table('character_knower',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='知られる人物'),
    sa.Column('knower_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='知る人物'),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='知る場所。その時刻にこの場所(配下も含む)に住む人物が知る'),
    sa.Column('start', sa.BIGINT(), autoincrement=False, nullable=True, comment='知った時刻。空なら初めから知っている'),
    sa.CheckConstraint('(knower_id IS NULL) <> (location_id IS NULL)', name=op.f('ck_character_knower_one_knower')),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name=op.f('character_knower_character_id_fkey')),
    sa.ForeignKeyConstraint(['knower_id'], ['character.id'], name=op.f('character_knower_knower_id_fkey')),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name=op.f('character_knower_location_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('character_knower_pkey')),
    sa.UniqueConstraint('character_id', 'knower_id', name=op.f('character_knower_character_id_knower_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('character_id', 'location_id', name=op.f('character_knower_character_id_location_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_character_knower_location_id'), 'character_knower', ['location_id'], unique=False)
    op.create_index(op.f('ix_character_knower_knower_id'), 'character_knower', ['knower_id'], unique=False)
    op.create_index(op.f('ix_character_knower_character_id'), 'character_knower', ['character_id'], unique=False)
    # ### end Alembic commands ###
    # 人物は自分の芯を知っていた(関係のある人物はその時刻ごとに変わるので写せない)
    op.execute("INSERT INTO character_knower (character_id, knower_id) SELECT id, id FROM character")
