"""人物のスキルとスキルの来歴_来歴を知る相手の表を足す

Revision ID: cc1b4e64b408
Revises: 8cedfefec3d8
Create Date: 2026-10-05 02:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc1b4e64b408'
down_revision: Union[str, Sequence[str], None] = '8cedfefec3d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_skill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False, comment='スキルを持つ人物'),
    sa.Column('name', sa.String(), nullable=False, comment='スキルの名前'),
    sa.Column('text', sa.String(), nullable=False, comment='スキルの本質(何ができるか・仕組み・限界)。作者だけが読み、人物役には渡さない'),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_skill_character_id'), 'character_skill', ['character_id'], unique=False)
    op.create_table('character_skill_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_skill_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=True, comment='起きた年(この来歴が効き始める年)。空なら年が決まっていない(話・人物役には渡さない)'),
    sa.Column('description', sa.String(), nullable=False, comment='来歴(身につけた・伸びた・衰えたなど、作中で起きたこと)'),
    sa.ForeignKeyConstraint(['character_skill_id'], ['character_skill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_skill_history_character_skill_id'), 'character_skill_history', ['character_skill_id'], unique=False)
    op.create_table('character_skill_history_knower',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('character_skill_history_id', sa.Integer(), nullable=False),
    sa.Column('knower_id', sa.Integer(), nullable=True, comment='知る人物'),
    sa.Column('location_id', sa.Integer(), nullable=True, comment='知る場所。その時刻にこの場所(配下も含む)に住む人物が知る'),
    sa.Column('start', sa.BigInteger(), nullable=True, comment='知った時刻。空なら初めから知っている'),
    sa.CheckConstraint('(knower_id IS NULL) <> (location_id IS NULL)', name='ck_character_skill_history_knower_one_knower'),
    sa.ForeignKeyConstraint(['character_skill_history_id'], ['character_skill_history.id'], ),
    sa.ForeignKeyConstraint(['knower_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_skill_history_id', 'knower_id'),
    sa.UniqueConstraint('character_skill_history_id', 'location_id')
    )
    op.create_index(op.f('ix_character_skill_history_knower_character_skill_history_id'), 'character_skill_history_knower', ['character_skill_history_id'], unique=False)
    op.create_index(op.f('ix_character_skill_history_knower_knower_id'), 'character_skill_history_knower', ['knower_id'], unique=False)
    op.create_index(op.f('ix_character_skill_history_knower_location_id'), 'character_skill_history_knower', ['location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_skill_history_knower_location_id'), table_name='character_skill_history_knower')
    op.drop_index(op.f('ix_character_skill_history_knower_knower_id'), table_name='character_skill_history_knower')
    op.drop_index(op.f('ix_character_skill_history_knower_character_skill_history_id'), table_name='character_skill_history_knower')
    op.drop_table('character_skill_history_knower')
    op.drop_index(op.f('ix_character_skill_history_character_skill_id'), table_name='character_skill_history')
    op.drop_table('character_skill_history')
    op.drop_index(op.f('ix_character_skill_character_id'), table_name='character_skill')
    op.drop_table('character_skill')
    # ### end Alembic commands ###
